<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SkillHubAI_Api</RootNamespace>
    <UserSecretsId>6b925ad2-f6f4-44cb-8799-7a3a445e415a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Search.Documents" Version="12.1.0-beta.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.10.0" />
    <PackageReference Include="Microsoft.Agents.AI.AzureAI" Version="1.0.0-rc5" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.0-preview.0" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion" Version="10.7.0-preview.1.26309.5" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion.MarkItDown" Version="10.7.0-preview.1.26309.5" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" Version="10.7.0" />
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="3.0.0-preview.26160.2" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" Version="3.0.0-preview.26160.2" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureAISearch" Version="1.74.0-preview" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IO" Version="4.3.0" />
  </ItemGroup>

</Project>
